#!/usr/bin/with-contenv ruby
require 'rubygems'
require 'json'
require 'httparty'
require 'highline/import'

require_relative '/var/lib/nowshowing/plexTv'

# Class to setup Report
#
# Author: Brian Stascavage
# Email: brian@stascavage.com
# Modified by: ninthwalker@gmail.com & groxypod@gmail.com
#
class Setup
    include HTTParty

    def initialize
        begin
            $config = Hash.new
#            $config = YAML.load_file(File.join(File.expand_path(File.dirname(__FILE__)), '/config/config.yaml') )
        rescue Errno::ENOENT => e
            abort('Configuration file not found.  Exiting...')
        end

        $config = { 'email' => 
                        { 'title'    => '' }, 
                    'plex'  =>
                        { 'server'   => '',
                          'api_key'  => '' },
                    'mail'  =>
                        { 'address'  => '',
                          'port'     => '',
                          'username' => '',
                          'password' => '',
                          'from'     => '',
                          'subject'  => '' },
                    'polling'  =>
                        { 'interval_movies'  => '', 
			  'interval_tv_shows' => '',
			  'interval_tv_episodes' => '' }
                  }
        $plex = PlexTv.new($config)
    end

    def setPlexApiKey
		plexusername = ENV['PLEX_USERNAME'] 
		plexpassword = ENV['PLEX_PASSWORD'] || []

		if plexpassword.empty?
			$config['plex']['api_key'] = ENV['PLEX_TOKEN']
		else
			auth = {:username => plexusername, :password => plexpassword}
			devices = $plex.get("/devices.xml", auth, true)

			devices['MediaContainer']['Device'].each do | device, index |
				if device['provides'] == 'server'
					$config['plex']['api_key'] = device['token']
					return true
				end 

				if devices['MediaContainer']['Device'].size - 1 == index
					puts "Cannot find Plex Server.  Exiting"
					abort
				end
			end
		end
	end

    def setServer
        $config['plex']['server'] = ENV['PLEX_SERVER_IP']
        if $config['plex']['server'].empty?
			$config['plex']['server'] = 'localhost'
        end
    end

    def setEmail
        $config['mail']['address'] = ENV['SMTP_SERVER']
        if $config['mail']['address'].empty?
            $config['mail']['address'] = 'smtp.gmail.com'
        end

        $config['mail']['port'] = ENV['SMTP_PORT']
        if $config['mail']['port'].empty?
            $config['mail']['port'] = 587
        end

        $config['mail']['username'] = ENV['EMAIL_USERNAME']
        $config['mail']['password'] = ENV['EMAIL_PASSWORD']

        $config['mail']['from'] = ENV['SENDER_DISPLAY_NAME']
        if $config['mail']['from'].empty?
            $config['mail']['from'] = 'Plex Server'
        end

        $config['mail']['subject'] = ENV['EMAIL_SUBJECT']
        if $config['mail']['subject'].empty?
            $config['mail']['subject'] = 'Plex Server Summary'
        end

        $config['email']['title'] = ENV['EMAIL_BODY_DISPLAY_TITLE']
        if $config['email']['title'].empty?
            $config['email']['title'] = 'Plex Server Summary'
        end
    end
    
    def setPolling
    	envint_movies = ENV['POLLING_INTERVAL']
	envint_tv_shows = ENV['POLLING_INTERVAL']
	envint_tv_episodes = ENV['POLLING_INTERVAL']
	
	envint_movies = envint_movies.to_i * 86400
	envint_tv_shows = envint_tv_shows.to_i * 86400
	envint_tv_episodes = envint_tv_episodes.to_i + 1
	
        $config['polling']['interval_movies'] = envint_movies
        if $config['polling']['interval_movies'].empty?
			$config['polling']['interval_movies'] = 604800
        end
	
	 $config['polling']['interval_tv_shows'] = envint_tv_shows
        if $config['polling']['interval_tv_shows'].empty?
			$config['polling']['interval_tv_shows'] = 604800
        end
	
	 $config['polling']['interval_tv_episodes'] = envint_tv_episodes
        if $config['polling']['interval_tv_episodes'].empty?
			$config['polling']['interval_tv_episodes'] = 8
        end
    end

    def start
        self.setServer
        self.setPlexApiKey
        self.setEmail
	self.setPolling

        File.open('/config/config.yaml', 'w') {|f| f.write $config.to_yaml }
    end
end

setup_agent = Setup.new
setup_agent.start
