#!/usr/bin/with-contenv sh

PUID=${PUID:-99}
PGID=${PGID:-100}

groupmod -o -g "$PGID" xyz
usermod -o -u "$PUID" xyz
chown -R xyz:xyz /opt
echo "
-----------------------------------------
              NowShowing
-----------------------------------------
          Brought to you by:
          
Ninthwalker
+
GroxyPod
+
Limen

-----------------------------------------
User xyz uid set to:  $(id -u xyz)
User xyz gid set to:  $(id -g xyz)
-----------------------------------------
"     
