#!/usr/bin/with-contenv sh

#Copies config files and creates advanced config file if not present
if [ -f /config/cfg/advanced.yaml ]; then
  echo "Advanced config file detected. Keeping existing files"
else
  # copy files incl advanced.yaml
  cp -Rp /opt/config/. /config/
  # set password to a random one
  php-cgi7 /opt/php/randomPass.php
fi

# Always load latest cron settings
ruby /usr/local/sbin/create-cron

#fail2ban start
fail2ban-client start

#read nowshowing_schedule.cron on container startup and add to crontab.
chown xyz:xyz /opt/nowshowing_schedule.cron
crontab -u xyz /opt/nowshowing_schedule.cron

#start cron
crond

echo "Please go to http://hostIP:hostPort/admin to configure settings"
